/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public enum EModelType {
  CatboostBinary(0),
  AppleCoreML(1),
  Cpp(2),
  Python(3),
  Json(4),
  Onnx(5),
  Pmml(6),
  CPUSnapshot(7);

  public final int swigValue() {
    return swigValue;
  }

  public static EModelType swigToEnum(int swigValue) {
    EModelType[] swigValues = EModelType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EModelType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EModelType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EModelType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EModelType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EModelType(EModelType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

