/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public enum EPredictionType {
  Probability,
  LogProbability,
  Class,
  RawFormulaVal,
  Exponent,
  RMSEWithUncertainty,
  InternalRawFormulaVal,
  VirtEnsembles,
  TotalUncertainty;

  public final int swigValue() {
    return swigValue;
  }

  public static EPredictionType swigToEnum(int swigValue) {
    EPredictionType[] swigValues = EPredictionType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (EPredictionType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + EPredictionType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private EPredictionType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private EPredictionType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private EPredictionType(EPredictionType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

