/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class IQuantizedFeaturesDataVisitor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IQuantizedFeaturesDataVisitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IQuantizedFeaturesDataVisitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IQuantizedFeaturesDataVisitor obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_IQuantizedFeaturesDataVisitor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Start(TDataMetaInfo metaInfo, int objectCount, TQuantizedFeaturesInfo quantizedFeaturesInfo) {
    native_implJNI.IQuantizedFeaturesDataVisitor_Start(swigCPtr, this, TDataMetaInfo.getCPtr(metaInfo), metaInfo, objectCount, TQuantizedFeaturesInfo.getCPtr(quantizedFeaturesInfo), quantizedFeaturesInfo);
  }

  public void AddGroupId(long[] groupIdData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddGroupId(swigCPtr, this, groupIdData);
  }

  public void AddSubgroupId(int[] subgroupIdData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddSubgroupId(swigCPtr, this, subgroupIdData);
  }

  public void AddTimestamp(long[] timestampData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddTimestamp(swigCPtr, this, timestampData);
  }

  public void AddFeature(TFeaturesLayout featuresLayout, int flatFeatureIdx, int objectCount, byte bitsPerDocumentFeature, TVector_i64 featureDataBuffer) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddFeature(swigCPtr, this, TFeaturesLayout.getCPtr(featuresLayout), featuresLayout, flatFeatureIdx, objectCount, bitsPerDocumentFeature, TVector_i64.getCPtr(featureDataBuffer), featureDataBuffer);
  }

  public void AddTarget(float[] targetData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddTarget__SWIG_0(swigCPtr, this, targetData);
  }

  public void AddTarget(TVector_TString targetData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddTarget__SWIG_1(swigCPtr, this, TVector_TString.getCPtr(targetData), targetData);
  }

  public void AddBaseline(int baselineIdx, float[] baselineData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddBaseline(swigCPtr, this, baselineIdx, baselineData);
  }

  public void AddWeight(float[] weightData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddWeight(swigCPtr, this, weightData);
  }

  public void AddGroupWeight(float[] groupWeightData) {
    native_implJNI.IQuantizedFeaturesDataVisitor_AddGroupWeight(swigCPtr, this, groupWeightData);
  }

  public void Finish() {
    native_implJNI.IQuantizedFeaturesDataVisitor_Finish(swigCPtr, this);
  }

}
