/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

