/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class SWIGTYPE_p_NCB__TGroupedPairsInfo {
  private transient long swigCPtr;

  protected SWIGTYPE_p_NCB__TGroupedPairsInfo(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_NCB__TGroupedPairsInfo() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_NCB__TGroupedPairsInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

