/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TCatBoostOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TCatBoostOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TCatBoostOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TCatBoostOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TCatBoostOptions(ETaskType taskType) throws Exception {
    this(native_implJNI.new_TCatBoostOptions(taskType.swigValue()), true);
  }

}
