/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TClassTargetPreprocessor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TClassTargetPreprocessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TClassTargetPreprocessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TClassTargetPreprocessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TClassTargetPreprocessor(String plainJsonParamsAsString, ERawTargetType rawTargetType, boolean trainDataHasWeights, boolean trainDataHasGroups) throws Exception {
    this(native_implJNI.new_TClassTargetPreprocessor(plainJsonParamsAsString, rawTargetType.swigValue(), trainDataHasWeights, trainDataHasGroups), true);
  }

  public boolean IsNeedToProcessDistinctTargetValues() throws Exception {
    return native_implJNI.TClassTargetPreprocessor_IsNeedToProcessDistinctTargetValues(swigCPtr, this);
  }

  public void ProcessDistinctFloatTargetValues(float[] distinctTargetValues) throws Exception {
    native_implJNI.TClassTargetPreprocessor_ProcessDistinctFloatTargetValues(swigCPtr, this, distinctTargetValues);
  }

  public void ProcessDistinctIntTargetValues(int[] distinctTargetValues) throws Exception {
    native_implJNI.TClassTargetPreprocessor_ProcessDistinctIntTargetValues(swigCPtr, this, distinctTargetValues);
  }

  public void ProcessDistinctStringTargetValues(TVector_TString distinctTargetValues) throws Exception {
    native_implJNI.TClassTargetPreprocessor_ProcessDistinctStringTargetValues(swigCPtr, this, TVector_TString.getCPtr(distinctTargetValues), distinctTargetValues);
  }

  public String GetLossFunction() throws Exception {
    return native_implJNI.TClassTargetPreprocessor_GetLossFunction(swigCPtr, this);
}

  public String GetUpdatedCatBoostOptionsJsonAsString() throws Exception {
    return native_implJNI.TClassTargetPreprocessor_GetUpdatedCatBoostOptionsJsonAsString(swigCPtr, this);
}

  public TVector_i8 GetSerializedLabelConverter() throws Exception {
    return new TVector_i8(native_implJNI.TClassTargetPreprocessor_GetSerializedLabelConverter(swigCPtr, this), true);
  }

  public TVector_float PreprocessFloatTarget(float[] targetValues) throws Exception {
    return new TVector_float(native_implJNI.TClassTargetPreprocessor_PreprocessFloatTarget(swigCPtr, this, targetValues), true);
  }

  public TVector_float PreprocessIntTarget(int[] targetValues) throws Exception {
    return new TVector_float(native_implJNI.TClassTargetPreprocessor_PreprocessIntTarget(swigCPtr, this, targetValues), true);
  }

  public TVector_float PreprocessStringTarget(TVector_TString targetValues) throws Exception {
    return new TVector_float(native_implJNI.TClassTargetPreprocessor_PreprocessStringTarget(swigCPtr, this, TVector_TString.getCPtr(targetValues), targetValues), true);
  }

}
