/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TDataProviderPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TDataProviderPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TDataProviderPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TDataProviderPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long GetObjectCount() {
    return native_implJNI.TDataProviderPtr_GetObjectCount(swigCPtr, this);
  }

  public TQuantizedObjectsDataProviderPtr GetQuantizedObjectsDataProvider() {
    return new TQuantizedObjectsDataProviderPtr(native_implJNI.TDataProviderPtr_GetQuantizedObjectsDataProvider(swigCPtr, this), true);
  }

  public TDataProviderPtr() {
    this(native_implJNI.new_TDataProviderPtr(), true);
  }

}
