/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TDataProviderBuilderOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TDataProviderBuilderOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TDataProviderBuilderOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TDataProviderBuilderOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TDataProviderBuilderOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxCpuRamUsage(java.math.BigInteger value) {
    native_implJNI.TDataProviderBuilderOptions_MaxCpuRamUsage_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getMaxCpuRamUsage() {
    return native_implJNI.TDataProviderBuilderOptions_MaxCpuRamUsage_get(swigCPtr, this);
  }

  public void setSkipCheck(boolean value) {
    native_implJNI.TDataProviderBuilderOptions_SkipCheck_set(swigCPtr, this, value);
  }

  public boolean getSkipCheck() {
    return native_implJNI.TDataProviderBuilderOptions_SkipCheck_get(swigCPtr, this);
  }

  public TDataProviderBuilderOptions() {
    this(native_implJNI.new_TDataProviderBuilderOptions(), true);
  }

}
