/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TDefaultQuantizedBin implements Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TDefaultQuantizedBin(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TDefaultQuantizedBin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TDefaultQuantizedBin(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIdx(long value) {
    native_implJNI.TDefaultQuantizedBin_Idx_set(swigCPtr, this, value);
  }

  public long getIdx() {
    return native_implJNI.TDefaultQuantizedBin_Idx_get(swigCPtr, this);
  }

  public void setFraction(float value) {
    native_implJNI.TDefaultQuantizedBin_Fraction_set(swigCPtr, this, value);
  }

  public float getFraction() {
    return native_implJNI.TDefaultQuantizedBin_Fraction_get(swigCPtr, this);
  }

            private void writeObject(ObjectOutputStream out) throws IOException {
                out.writeLong(this.getIdx());
                out.writeFloat(this.getFraction());
            }

            private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
                this.swigCPtr = native_implJNI.new_TDefaultQuantizedBin();
                this.swigCMemOwn = true;

                this.setIdx(in.readLong());
                this.setFraction(in.readFloat());
            }
        
  public TDefaultQuantizedBin() {
    this(native_implJNI.new_TDefaultQuantizedBin(), true);
  }

}
