/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TDsvFormatOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TDsvFormatOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TDsvFormatOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TDsvFormatOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TDsvFormatOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHasHeader(boolean value) {
    native_implJNI.TDsvFormatOptions_HasHeader_set(swigCPtr, this, value);
  }

  public boolean getHasHeader() {
    return native_implJNI.TDsvFormatOptions_HasHeader_get(swigCPtr, this);
  }

  public void setDelimiter(char value) {
    native_implJNI.TDsvFormatOptions_Delimiter_set(swigCPtr, this, value);
  }

  public char getDelimiter() {
    return native_implJNI.TDsvFormatOptions_Delimiter_get(swigCPtr, this);
  }

  public void setNumVectorDelimiter(char value) {
    native_implJNI.TDsvFormatOptions_NumVectorDelimiter_set(swigCPtr, this, value);
  }

  public char getNumVectorDelimiter() {
    return native_implJNI.TDsvFormatOptions_NumVectorDelimiter_get(swigCPtr, this);
  }

  public void setIgnoreCsvQuoting(boolean value) {
    native_implJNI.TDsvFormatOptions_IgnoreCsvQuoting_set(swigCPtr, this, value);
  }

  public boolean getIgnoreCsvQuoting() {
    return native_implJNI.TDsvFormatOptions_IgnoreCsvQuoting_get(swigCPtr, this);
  }

  public TDsvFormatOptions() {
    this(native_implJNI.new_TDsvFormatOptions(), true);
  }

}
