/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TEstimatedForCPUObjectsDataProviders {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TEstimatedForCPUObjectsDataProviders(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TEstimatedForCPUObjectsDataProviders obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TEstimatedForCPUObjectsDataProviders(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLearn(TQuantizedObjectsDataProviderPtr value) {
    native_implJNI.TEstimatedForCPUObjectsDataProviders_Learn_set(swigCPtr, this, TQuantizedObjectsDataProviderPtr.getCPtr(value), value);
  }

  public TQuantizedObjectsDataProviderPtr getLearn() {
    long cPtr = native_implJNI.TEstimatedForCPUObjectsDataProviders_Learn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TQuantizedObjectsDataProviderPtr(cPtr, false);
  }

  public void setTest(TVector_TQuantizedObjectsDataProviderPtr value) {
    native_implJNI.TEstimatedForCPUObjectsDataProviders_Test_set(swigCPtr, this, TVector_TQuantizedObjectsDataProviderPtr.getCPtr(value), value);
  }

  public TVector_TQuantizedObjectsDataProviderPtr getTest() {
    long cPtr = native_implJNI.TEstimatedForCPUObjectsDataProviders_Test_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TVector_TQuantizedObjectsDataProviderPtr(cPtr, false);
  }

  public TEstimatedForCPUObjectsDataProviders() {
    this(native_implJNI.new_TEstimatedForCPUObjectsDataProviders(), true);
  }

}
