/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TFeaturesLayoutPtr implements Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TFeaturesLayoutPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TFeaturesLayoutPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TFeaturesLayoutPtr obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TFeaturesLayoutPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TFeaturesLayout __deref__() {
    long cPtr = native_implJNI.TFeaturesLayoutPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new TFeaturesLayout(cPtr, false);
  }

  public TFeaturesLayout Get() {
    long cPtr = native_implJNI.TFeaturesLayoutPtr_Get(swigCPtr, this);
    return (cPtr == 0) ? null : new TFeaturesLayout(cPtr, false);
  }

  public void Set(TFeaturesLayout t) {
    native_implJNI.TFeaturesLayoutPtr_Set(swigCPtr, this, TFeaturesLayout.getCPtr(t), t);
  }

        public TFeaturesLayoutPtr(TFeaturesLayout pointee) {
            this();
            if (pointee != null) {
                pointee.releaseMem();
                this.Set(pointee);
            }
        }

        private void writeObject(ObjectOutputStream out) throws IOException {
            out.writeObject(this.Get());
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TFeaturesLayoutPtr();
            this.swigCMemOwn = true;

            TFeaturesLayout pointee = (TFeaturesLayout)in.readObject();
            if (pointee != null) {
                pointee.releaseMem();
                this.Set(pointee);
            }
        }

        public boolean equals(Object obj) {
            if (obj instanceof TFeaturesLayoutPtr) {
                boolean ptrEqual = (((TFeaturesLayoutPtr)obj).swigCPtr == this.swigCPtr);
                if (ptrEqual) {
                    return true;
                } else {
                    return this.equalsImpl(((TFeaturesLayoutPtr)obj).Get());
                }
            } else {
                return false;
            }
        }
    
  public TFeaturesLayoutPtr() {
    this(native_implJNI.new_TFeaturesLayoutPtr(), true);
  }

  public void Init(TVector_TFeatureMetaInfo data) throws Exception {
    native_implJNI.TFeaturesLayoutPtr_Init(swigCPtr, this, TVector_TFeatureMetaInfo.getCPtr(data), data);
  }

  public TVector_TString GetExternalFeatureIds() throws Exception {
    return new TVector_TString(native_implJNI.TFeaturesLayoutPtr_GetExternalFeatureIds(swigCPtr, this), true);
  }

  public long GetExternalFeatureCount() {
    return native_implJNI.TFeaturesLayoutPtr_GetExternalFeatureCount(swigCPtr, this);
  }

  public TVector_TFeatureMetaInfo GetExternalFeaturesMetaInfoAsVector() throws Exception {
    return new TVector_TFeatureMetaInfo(native_implJNI.TFeaturesLayoutPtr_GetExternalFeaturesMetaInfoAsVector(swigCPtr, this), true);
  }

  public boolean equalsImpl(TFeaturesLayout rhs) {
    return native_implJNI.TFeaturesLayoutPtr_equalsImpl(swigCPtr, this, TFeaturesLayout.getCPtr(rhs), rhs);
  }

}
