/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TFeatureMetaInfo implements Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TFeatureMetaInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TFeatureMetaInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TFeatureMetaInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(EFeatureType value) {
    native_implJNI.TFeatureMetaInfo_Type_set(swigCPtr, this, value.swigValue());
  }

  public EFeatureType getType() {
    return EFeatureType.swigToEnum(native_implJNI.TFeatureMetaInfo_Type_get(swigCPtr, this));
  }

  public void setName(String value) {
    native_implJNI.TFeatureMetaInfo_Name_set(swigCPtr, this, value);
  }

  public String getName() {
    return native_implJNI.TFeatureMetaInfo_Name_get(swigCPtr, this);
}

  public void setIsSparse(boolean value) {
    native_implJNI.TFeatureMetaInfo_IsSparse_set(swigCPtr, this, value);
  }

  public boolean getIsSparse() {
    return native_implJNI.TFeatureMetaInfo_IsSparse_get(swigCPtr, this);
  }

  public void setIsIgnored(boolean value) {
    native_implJNI.TFeatureMetaInfo_IsIgnored_set(swigCPtr, this, value);
  }

  public boolean getIsIgnored() {
    return native_implJNI.TFeatureMetaInfo_IsIgnored_get(swigCPtr, this);
  }

  public void setIsAvailable(boolean value) {
    native_implJNI.TFeatureMetaInfo_IsAvailable_set(swigCPtr, this, value);
  }

  public boolean getIsAvailable() {
    return native_implJNI.TFeatureMetaInfo_IsAvailable_get(swigCPtr, this);
  }

  public TFeatureMetaInfo() {
    this(native_implJNI.new_TFeatureMetaInfo(), true);
  }

            private void writeObject(ObjectOutputStream out) throws IOException {
                out.writeUnshared(this.getType());
                out.writeUTF(this.getName());
                out.writeBoolean(this.getIsSparse());
                out.writeBoolean(this.getIsIgnored());
                out.writeBoolean(this.getIsAvailable());
            }

            private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
                this.swigCPtr = native_implJNI.new_TFeatureMetaInfo();
                this.swigCMemOwn = true;

                this.setType((EFeatureType)in.readUnshared());
                this.setName(in.readUTF());
                this.setIsSparse(in.readBoolean());
                this.setIsIgnored(in.readBoolean());
                this.setIsAvailable(in.readBoolean());
            }
        
  public boolean equalsImpl(TFeatureMetaInfo rhs) {
    return native_implJNI.TFeatureMetaInfo_equalsImpl(swigCPtr, this, TFeatureMetaInfo.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TFeatureMetaInfo) {
        boolean ptrEqual = (((TFeatureMetaInfo)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TFeatureMetaInfo)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


}
