/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TLocalExecutor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TLocalExecutor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TLocalExecutor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TLocalExecutor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(int threadCount) {
    native_implJNI.TLocalExecutor_Init(swigCPtr, this, threadCount);
  }

  public TLocalExecutor() {
    this(native_implJNI.new_TLocalExecutor(), true);
  }

}
