/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TMaybe_TString implements Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TMaybe_TString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TMaybe_TString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TMaybe_TString obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TMaybe_TString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TMaybe_TString() {
    this(native_implJNI.new_TMaybe_TString__SWIG_0(), true);
  }

  public TMaybe_TString(String arg) {
    this(native_implJNI.new_TMaybe_TString__SWIG_1(arg), true);
  }

  public boolean Defined() {
    return native_implJNI.TMaybe_TString_Defined(swigCPtr, this);
  }

  public String GetRef() {
    return native_implJNI.TMaybe_TString_GetRef(swigCPtr, this);
}

  public void MoveInto(TMaybe_TString rhs) {
    native_implJNI.TMaybe_TString_MoveInto(swigCPtr, this, TMaybe_TString.getCPtr(rhs), rhs);
  }

        private void writeObject(ObjectOutputStream out) throws IOException {
            boolean isDefined = this.Defined();
            out.writeBoolean(isDefined);
            if (isDefined) {
                out.writeUnshared(this.GetRef());
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TMaybe_TString__SWIG_0();
            this.swigCMemOwn = true;

            boolean isDefined = in.readBoolean();
            if (isDefined) {
                this.MoveInto(new TMaybe_TString((String)in.readUnshared()));
            }
        }
    
  public boolean equalsImpl(TMaybe_TString rhs) {
    return native_implJNI.TMaybe_TString_equalsImpl(swigCPtr, this, TMaybe_TString.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TMaybe_TString) {
        boolean ptrEqual = (((TMaybe_TString)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TMaybe_TString)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


}
