/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TMaybe_TDataColumnsMetaInfo implements Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TMaybe_TDataColumnsMetaInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TMaybe_TDataColumnsMetaInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TMaybe_TDataColumnsMetaInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TMaybe_TDataColumnsMetaInfo() {
    this(native_implJNI.new_TMaybe_TDataColumnsMetaInfo__SWIG_0(), true);
  }

  public TMaybe_TDataColumnsMetaInfo(TDataColumnsMetaInfo arg) {
    this(native_implJNI.new_TMaybe_TDataColumnsMetaInfo__SWIG_1(TDataColumnsMetaInfo.getCPtr(arg), arg), true);
  }

  public boolean Defined() {
    return native_implJNI.TMaybe_TDataColumnsMetaInfo_Defined(swigCPtr, this);
  }

  public TDataColumnsMetaInfo GetRef() {
    return new TDataColumnsMetaInfo(native_implJNI.TMaybe_TDataColumnsMetaInfo_GetRef(swigCPtr, this), false);
  }

  public void MoveInto(TMaybe_TDataColumnsMetaInfo rhs) {
    native_implJNI.TMaybe_TDataColumnsMetaInfo_MoveInto(swigCPtr, this, TMaybe_TDataColumnsMetaInfo.getCPtr(rhs), rhs);
  }

        private void writeObject(ObjectOutputStream out) throws IOException {
            boolean isDefined = this.Defined();
            out.writeBoolean(isDefined);
            if (isDefined) {
                out.writeUnshared(this.GetRef());
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TMaybe_TDataColumnsMetaInfo__SWIG_0();
            this.swigCMemOwn = true;

            boolean isDefined = in.readBoolean();
            if (isDefined) {
                this.MoveInto(new TMaybe_TDataColumnsMetaInfo((TDataColumnsMetaInfo)in.readUnshared()));
            }
        }
    
  public boolean equalsImpl(TMaybe_TDataColumnsMetaInfo rhs) {
    return native_implJNI.TMaybe_TDataColumnsMetaInfo_equalsImpl(swigCPtr, this, TMaybe_TDataColumnsMetaInfo.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TMaybe_TDataColumnsMetaInfo) {
        boolean ptrEqual = (((TMaybe_TDataColumnsMetaInfo)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TMaybe_TDataColumnsMetaInfo)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


}
