/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TRawDatasetRow {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TRawDatasetRow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TRawDatasetRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TRawDatasetRow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGroupId(long value) {
    native_implJNI.TRawDatasetRow_GroupId_set(swigCPtr, this, value);
  }

  public long getGroupId() {
    return native_implJNI.TRawDatasetRow_GroupId_get(swigCPtr, this);
  }

  public void setSubgroupId(int value) {
    native_implJNI.TRawDatasetRow_SubgroupId_set(swigCPtr, this, value);
  }

  public int getSubgroupId() {
    return native_implJNI.TRawDatasetRow_SubgroupId_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    native_implJNI.TRawDatasetRow_Timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return native_implJNI.TRawDatasetRow_Timestamp_get(swigCPtr, this);
  }

  public void setStringTarget(String value) {
    native_implJNI.TRawDatasetRow_StringTarget_set(swigCPtr, this, value);
  }

  public String getStringTarget() {
    return native_implJNI.TRawDatasetRow_StringTarget_get(swigCPtr, this);
}

  public void setFloatTarget(float value) {
    native_implJNI.TRawDatasetRow_FloatTarget_set(swigCPtr, this, value);
  }

  public float getFloatTarget() {
    return native_implJNI.TRawDatasetRow_FloatTarget_get(swigCPtr, this);
  }

  public void setWeight(float value) {
    native_implJNI.TRawDatasetRow_Weight_set(swigCPtr, this, value);
  }

  public float getWeight() {
    return native_implJNI.TRawDatasetRow_Weight_get(swigCPtr, this);
  }

  public void setGroupWeight(float value) {
    native_implJNI.TRawDatasetRow_GroupWeight_set(swigCPtr, this, value);
  }

  public float getGroupWeight() {
    return native_implJNI.TRawDatasetRow_GroupWeight_get(swigCPtr, this);
  }

  public void setSparseFloatFeaturesIndices(TVector_i32 value) {
    native_implJNI.TRawDatasetRow_SparseFloatFeaturesIndices_set(swigCPtr, this, TVector_i32.getCPtr(value), value);
  }

  public TVector_i32 getSparseFloatFeaturesIndices() {
    long cPtr = native_implJNI.TRawDatasetRow_SparseFloatFeaturesIndices_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TVector_i32(cPtr, false);
  }

  public void setSparseFloatFeaturesValues(TVector_double value) {
    native_implJNI.TRawDatasetRow_SparseFloatFeaturesValues_set(swigCPtr, this, TVector_double.getCPtr(value), value);
  }

  public TVector_double getSparseFloatFeaturesValues() {
    long cPtr = native_implJNI.TRawDatasetRow_SparseFloatFeaturesValues_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TVector_double(cPtr, false);
  }

  public void GetDenseFloatFeatures(double[] output) {
    native_implJNI.TRawDatasetRow_GetDenseFloatFeatures(swigCPtr, this, output);
  }

  public void GetBaselines(double[] output) {
    native_implJNI.TRawDatasetRow_GetBaselines(swigCPtr, this, output);
  }

  public TRawDatasetRow() {
    this(native_implJNI.new_TRawDatasetRow(), true);
  }

}
