/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TShapInteractionValuesResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TShapInteractionValuesResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TShapInteractionValuesResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TShapInteractionValuesResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TShapInteractionValuesResult(SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t data) {
    this(native_implJNI.new_TShapInteractionValuesResult(SWIGTYPE_p_TVectorT_TVectorT_TVectorT_TVectorT_double_t_t_t_t.getCPtr(data)), true);
  }

  public int GetObjectCount() throws Exception {
    return native_implJNI.TShapInteractionValuesResult_GetObjectCount(swigCPtr, this);
  }

  public int GetShapInteractionValuesCount() throws Exception {
    return native_implJNI.TShapInteractionValuesResult_GetShapInteractionValuesCount(swigCPtr, this);
  }

  public TVector_double Get(int objectIdx, int dimensionIdx) throws Exception {
    return new TVector_double(native_implJNI.TShapInteractionValuesResult_Get__SWIG_0(swigCPtr, this, objectIdx, dimensionIdx), true);
  }

  public TVector_double Get(int objectIdx) throws Exception {
    return new TVector_double(native_implJNI.TShapInteractionValuesResult_Get__SWIG_1(swigCPtr, this, objectIdx), true);
  }

}
