/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TStringOutWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TStringOutWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TStringOutWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TStringOutWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TStringOutWrapper(SWIGTYPE_p_TString out) {
    this(native_implJNI.new_TStringOutWrapper(SWIGTYPE_p_TString.getCPtr(out)), true);
  }

  public void Assign(byte[] data, int length) throws Exception {
    native_implJNI.TStringOutWrapper_Assign(swigCPtr, this, data, length);
  }

}
