/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;

public class TTargetStatsForCtrs {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TTargetStatsForCtrs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TTargetStatsForCtrs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TTargetStatsForCtrs obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TTargetStatsForCtrs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLearnTargetClass(SWIGTYPE_p_TVectorT_TVectorT_int_t_t value) {
    native_implJNI.TTargetStatsForCtrs_LearnTargetClass_set(swigCPtr, this, SWIGTYPE_p_TVectorT_TVectorT_int_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_TVectorT_TVectorT_int_t_t getLearnTargetClass() {
    long cPtr = native_implJNI.TTargetStatsForCtrs_LearnTargetClass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TVectorT_TVectorT_int_t_t(cPtr, false);
  }

  public void setTargetClassesCount(SWIGTYPE_p_TVectorT_int_t value) {
    native_implJNI.TTargetStatsForCtrs_TargetClassesCount_set(swigCPtr, this, SWIGTYPE_p_TVectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_TVectorT_int_t getTargetClassesCount() {
    long cPtr = native_implJNI.TTargetStatsForCtrs_TargetClassesCount_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_TVectorT_int_t(cPtr, false);
  }

  public TTargetStatsForCtrs() {
    this(native_implJNI.new_TTargetStatsForCtrs(), true);
  }

}
