/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_i8 extends java.util.AbstractList<Byte> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_i8(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_i8 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_i8(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_i8_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_i8_reserve(swigCPtr, this, new_cap);
  }

  public byte getImpl(int index) {
    return native_implJNI.TVector_i8_getImpl(swigCPtr, this, index);
  }

  public byte setImpl(int index, byte element) {
    return native_implJNI.TVector_i8_setImpl(swigCPtr, this, index, element);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_i8_sizeImpl(swigCPtr, this);
  }

  public void addImpl(byte element) {
    native_implJNI.TVector_i8_addImpl__SWIG_0(swigCPtr, this, element);
  }

  public void addImpl(int index, byte element) {
    native_implJNI.TVector_i8_addImpl__SWIG_1(swigCPtr, this, index, element);
  }

  public byte removeImpl(int index) {
    return native_implJNI.TVector_i8_removeImpl(swigCPtr, this, index);
  }

        public TVector_i8(byte[] elements) {
            this();
            reserve(elements.length);
            for (byte element : elements) {
                addImpl(element);
            }
        }

        public TVector_i8(Iterable<Byte> elements) {
            this();
            for (byte element : elements) {
                addImpl(element);
            }
        }

        public Byte get(int index) {
            return getImpl(index);
        }

        public Byte set(int index, Byte element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(Byte element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, Byte element) {
            modCount++;
            addImpl(index, element);
        }

        public Byte remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_i8();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((Byte)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_i8 rhs) {
    return native_implJNI.TVector_i8_equalsImpl(swigCPtr, this, TVector_i8.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_i8) {
        boolean ptrEqual = (((TVector_i8)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_i8)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


            public byte[] toPrimitiveArray() {
                return native_implJNI.toPrimitiveArrayImpl_i8(swigCPtr, this);
            }

            // valid only until next reallocation of TVector, so, use with caution.
            public java.nio.ByteBuffer asDirectByteBuffer() {
                return (java.nio.ByteBuffer)native_implJNI.asDirectByteBufferImpl_i8(swigCPtr, this);
            }
        
  public TVector_i8() {
    this(native_implJNI.new_TVector_i8(), true);
  }

}
