/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_TMaybeOwningConstArrayHolder_float extends java.util.AbstractList<float[]> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_TMaybeOwningConstArrayHolder_float(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_TMaybeOwningConstArrayHolder_float obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TVector_TMaybeOwningConstArrayHolder_float obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_TMaybeOwningConstArrayHolder_float(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_reserve(swigCPtr, this, new_cap);
  }

  public float[] getImpl(int index) {
    return native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_getImpl(swigCPtr, this, index);
}

  public float[] setImpl(int index, float[] element) {
    return native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_setImpl(swigCPtr, this, index, element);
}

  public int sizeImpl() {
    return native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_sizeImpl(swigCPtr, this);
  }

  public void addImpl(float[] element) {
    native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_addImpl__SWIG_0(swigCPtr, this, element);
  }

  public void addImpl(int index, float[] element) {
    native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_addImpl__SWIG_1(swigCPtr, this, index, element);
  }

  public float[] removeImpl(int index) {
    return native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_removeImpl(swigCPtr, this, index);
}

        public TVector_TMaybeOwningConstArrayHolder_float(float[][] elements) {
            this();
            reserve(elements.length);
            for (float[] element : elements) {
                addImpl(element);
            }
        }

        public TVector_TMaybeOwningConstArrayHolder_float(Iterable<float[]> elements) {
            this();
            for (float[] element : elements) {
                addImpl(element);
            }
        }

        public float[] get(int index) {
            return getImpl(index);
        }

        public float[] set(int index, float[] element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(float[] element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, float[] element) {
            modCount++;
            addImpl(index, element);
        }

        public float[] remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_TMaybeOwningConstArrayHolder_float();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((float[])in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_TMaybeOwningConstArrayHolder_float rhs) {
    return native_implJNI.TVector_TMaybeOwningConstArrayHolder_float_equalsImpl(swigCPtr, this, TVector_TMaybeOwningConstArrayHolder_float.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_TMaybeOwningConstArrayHolder_float) {
        boolean ptrEqual = (((TVector_TMaybeOwningConstArrayHolder_float)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_TMaybeOwningConstArrayHolder_float)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_TMaybeOwningConstArrayHolder_float() {
    this(native_implJNI.new_TVector_TMaybeOwningConstArrayHolder_float(), true);
  }

}
