/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_TColumn extends java.util.AbstractList<TColumn> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_TColumn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_TColumn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_TColumn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_TColumn_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_TColumn_reserve(swigCPtr, this, new_cap);
  }

  public TColumn getImpl(int index) {
    return new TColumn(native_implJNI.TVector_TColumn_getImpl(swigCPtr, this, index), false);
  }

  public TColumn setImpl(int index, TColumn element) {
    return new TColumn(native_implJNI.TVector_TColumn_setImpl(swigCPtr, this, index, TColumn.getCPtr(element), element), true);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_TColumn_sizeImpl(swigCPtr, this);
  }

  public void addImpl(TColumn element) {
    native_implJNI.TVector_TColumn_addImpl__SWIG_0(swigCPtr, this, TColumn.getCPtr(element), element);
  }

  public void addImpl(int index, TColumn element) {
    native_implJNI.TVector_TColumn_addImpl__SWIG_1(swigCPtr, this, index, TColumn.getCPtr(element), element);
  }

  public TColumn removeImpl(int index) {
    return new TColumn(native_implJNI.TVector_TColumn_removeImpl(swigCPtr, this, index), true);
  }

        public TVector_TColumn(TColumn[] elements) {
            this();
            reserve(elements.length);
            for (TColumn element : elements) {
                addImpl(element);
            }
        }

        public TVector_TColumn(Iterable<TColumn> elements) {
            this();
            for (TColumn element : elements) {
                addImpl(element);
            }
        }

        public TColumn get(int index) {
            return getImpl(index);
        }

        public TColumn set(int index, TColumn element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(TColumn element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, TColumn element) {
            modCount++;
            addImpl(index, element);
        }

        public TColumn remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_TColumn();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((TColumn)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_TColumn rhs) {
    return native_implJNI.TVector_TColumn_equalsImpl(swigCPtr, this, TVector_TColumn.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_TColumn) {
        boolean ptrEqual = (((TVector_TColumn)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_TColumn)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_TColumn() {
    this(native_implJNI.new_TVector_TColumn(), true);
  }

}
