/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_i64 extends java.util.AbstractList<Long> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_i64(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_i64 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_i64(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_i64_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_i64_reserve(swigCPtr, this, new_cap);
  }

  public long getImpl(int index) {
    return native_implJNI.TVector_i64_getImpl(swigCPtr, this, index);
  }

  public long setImpl(int index, long element) {
    return native_implJNI.TVector_i64_setImpl(swigCPtr, this, index, element);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_i64_sizeImpl(swigCPtr, this);
  }

  public void addImpl(long element) {
    native_implJNI.TVector_i64_addImpl__SWIG_0(swigCPtr, this, element);
  }

  public void addImpl(int index, long element) {
    native_implJNI.TVector_i64_addImpl__SWIG_1(swigCPtr, this, index, element);
  }

  public long removeImpl(int index) {
    return native_implJNI.TVector_i64_removeImpl(swigCPtr, this, index);
  }

        public TVector_i64(long[] elements) {
            this();
            reserve(elements.length);
            for (long element : elements) {
                addImpl(element);
            }
        }

        public TVector_i64(Iterable<Long> elements) {
            this();
            for (long element : elements) {
                addImpl(element);
            }
        }

        public Long get(int index) {
            return getImpl(index);
        }

        public Long set(int index, Long element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(Long element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, Long element) {
            modCount++;
            addImpl(index, element);
        }

        public Long remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_i64();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((Long)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_i64 rhs) {
    return native_implJNI.TVector_i64_equalsImpl(swigCPtr, this, TVector_i64.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_i64) {
        boolean ptrEqual = (((TVector_i64)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_i64)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


            public long[] toPrimitiveArray() {
                return native_implJNI.toPrimitiveArrayImpl_i64(swigCPtr, this);
            }

            // valid only until next reallocation of TVector, so, use with caution.
            public java.nio.ByteBuffer asDirectByteBuffer() {
                return (java.nio.ByteBuffer)native_implJNI.asDirectByteBufferImpl_i64(swigCPtr, this);
            }
        
  public TVector_i64() {
    this(native_implJNI.new_TVector_i64(), true);
  }

}
