/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_TString extends java.util.AbstractList<String> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_TString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_TString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_TString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_TString_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_TString_reserve(swigCPtr, this, new_cap);
  }

  public String getImpl(int index) {
    return native_implJNI.TVector_TString_getImpl(swigCPtr, this, index);
}

  public String setImpl(int index, String element) {
    return native_implJNI.TVector_TString_setImpl(swigCPtr, this, index, element);
}

  public int sizeImpl() {
    return native_implJNI.TVector_TString_sizeImpl(swigCPtr, this);
  }

  public void addImpl(String element) {
    native_implJNI.TVector_TString_addImpl__SWIG_0(swigCPtr, this, element);
  }

  public void addImpl(int index, String element) {
    native_implJNI.TVector_TString_addImpl__SWIG_1(swigCPtr, this, index, element);
  }

  public String removeImpl(int index) {
    return native_implJNI.TVector_TString_removeImpl(swigCPtr, this, index);
}

        public TVector_TString(String[] elements) {
            this();
            reserve(elements.length);
            for (String element : elements) {
                addImpl(element);
            }
        }

        public TVector_TString(Iterable<String> elements) {
            this();
            for (String element : elements) {
                addImpl(element);
            }
        }

        public String get(int index) {
            return getImpl(index);
        }

        public String set(int index, String element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(String element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, String element) {
            modCount++;
            addImpl(index, element);
        }

        public String remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_TString();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((String)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_TString rhs) {
    return native_implJNI.TVector_TString_equalsImpl(swigCPtr, this, TVector_TString.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_TString) {
        boolean ptrEqual = (((TVector_TString)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_TString)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_TString() {
    this(native_implJNI.new_TVector_TString(), true);
  }

}
