/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_const_TFullModel_ptr extends java.util.AbstractList<TFullModel> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_const_TFullModel_ptr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_const_TFullModel_ptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_const_TFullModel_ptr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_const_TFullModel_ptr_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_const_TFullModel_ptr_reserve(swigCPtr, this, new_cap);
  }

  public TFullModel getImpl(int index) {
    long cPtr = native_implJNI.TVector_const_TFullModel_ptr_getImpl(swigCPtr, this, index);
    return (cPtr == 0) ? null : new TFullModel(cPtr, false);
  }

  public TFullModel setImpl(int index, TFullModel element) {
    long cPtr = native_implJNI.TVector_const_TFullModel_ptr_setImpl(swigCPtr, this, index, TFullModel.getCPtr(element), element);
    return (cPtr == 0) ? null : new TFullModel(cPtr, false);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_const_TFullModel_ptr_sizeImpl(swigCPtr, this);
  }

  public void addImpl(TFullModel element) {
    native_implJNI.TVector_const_TFullModel_ptr_addImpl__SWIG_0(swigCPtr, this, TFullModel.getCPtr(element), element);
  }

  public void addImpl(int index, TFullModel element) {
    native_implJNI.TVector_const_TFullModel_ptr_addImpl__SWIG_1(swigCPtr, this, index, TFullModel.getCPtr(element), element);
  }

  public TFullModel removeImpl(int index) {
    long cPtr = native_implJNI.TVector_const_TFullModel_ptr_removeImpl(swigCPtr, this, index);
    return (cPtr == 0) ? null : new TFullModel(cPtr, false);
  }

        public TVector_const_TFullModel_ptr(TFullModel[] elements) {
            this();
            reserve(elements.length);
            for (TFullModel element : elements) {
                addImpl(element);
            }
        }

        public TVector_const_TFullModel_ptr(Iterable<TFullModel> elements) {
            this();
            for (TFullModel element : elements) {
                addImpl(element);
            }
        }

        public TFullModel get(int index) {
            return getImpl(index);
        }

        public TFullModel set(int index, TFullModel element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(TFullModel element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, TFullModel element) {
            modCount++;
            addImpl(index, element);
        }

        public TFullModel remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_const_TFullModel_ptr();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((TFullModel)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_const_TFullModel_ptr rhs) {
    return native_implJNI.TVector_const_TFullModel_ptr_equalsImpl(swigCPtr, this, TVector_const_TFullModel_ptr.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_const_TFullModel_ptr) {
        boolean ptrEqual = (((TVector_const_TFullModel_ptr)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_const_TFullModel_ptr)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_const_TFullModel_ptr() {
    this(native_implJNI.new_TVector_const_TFullModel_ptr(), true);
  }

}
