/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_TQuantizedObjectsDataProviderPtr extends java.util.AbstractList<TQuantizedObjectsDataProviderPtr> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_TQuantizedObjectsDataProviderPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_TQuantizedObjectsDataProviderPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_TQuantizedObjectsDataProviderPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_reserve(swigCPtr, this, new_cap);
  }

  public TQuantizedObjectsDataProviderPtr getImpl(int index) {
    return new TQuantizedObjectsDataProviderPtr(native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_getImpl(swigCPtr, this, index), false);
  }

  public TQuantizedObjectsDataProviderPtr setImpl(int index, TQuantizedObjectsDataProviderPtr element) {
    return new TQuantizedObjectsDataProviderPtr(native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_setImpl(swigCPtr, this, index, TQuantizedObjectsDataProviderPtr.getCPtr(element), element), true);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_sizeImpl(swigCPtr, this);
  }

  public void addImpl(TQuantizedObjectsDataProviderPtr element) {
    native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_addImpl__SWIG_0(swigCPtr, this, TQuantizedObjectsDataProviderPtr.getCPtr(element), element);
  }

  public void addImpl(int index, TQuantizedObjectsDataProviderPtr element) {
    native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_addImpl__SWIG_1(swigCPtr, this, index, TQuantizedObjectsDataProviderPtr.getCPtr(element), element);
  }

  public TQuantizedObjectsDataProviderPtr removeImpl(int index) {
    return new TQuantizedObjectsDataProviderPtr(native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_removeImpl(swigCPtr, this, index), true);
  }

        public TVector_TQuantizedObjectsDataProviderPtr(TQuantizedObjectsDataProviderPtr[] elements) {
            this();
            reserve(elements.length);
            for (TQuantizedObjectsDataProviderPtr element : elements) {
                addImpl(element);
            }
        }

        public TVector_TQuantizedObjectsDataProviderPtr(Iterable<TQuantizedObjectsDataProviderPtr> elements) {
            this();
            for (TQuantizedObjectsDataProviderPtr element : elements) {
                addImpl(element);
            }
        }

        public TQuantizedObjectsDataProviderPtr get(int index) {
            return getImpl(index);
        }

        public TQuantizedObjectsDataProviderPtr set(int index, TQuantizedObjectsDataProviderPtr element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(TQuantizedObjectsDataProviderPtr element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, TQuantizedObjectsDataProviderPtr element) {
            modCount++;
            addImpl(index, element);
        }

        public TQuantizedObjectsDataProviderPtr remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_TQuantizedObjectsDataProviderPtr();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((TQuantizedObjectsDataProviderPtr)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_TQuantizedObjectsDataProviderPtr rhs) {
    return native_implJNI.TVector_TQuantizedObjectsDataProviderPtr_equalsImpl(swigCPtr, this, TVector_TQuantizedObjectsDataProviderPtr.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_TQuantizedObjectsDataProviderPtr) {
        boolean ptrEqual = (((TVector_TQuantizedObjectsDataProviderPtr)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_TQuantizedObjectsDataProviderPtr)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_TQuantizedObjectsDataProviderPtr() {
    this(native_implJNI.new_TVector_TQuantizedObjectsDataProviderPtr(), true);
  }

}
