/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl;
import java.io.*;
public class TVector_TDataProviderPtr extends java.util.AbstractList<TDataProviderPtr> implements java.util.RandomAccess,Serializable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TVector_TDataProviderPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TVector_TDataProviderPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        native_implJNI.delete_TVector_TDataProviderPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void yresize(long new_size) {
    native_implJNI.TVector_TDataProviderPtr_yresize(swigCPtr, this, new_size);
  }

  public void reserve(long new_cap) {
    native_implJNI.TVector_TDataProviderPtr_reserve(swigCPtr, this, new_cap);
  }

  public TDataProviderPtr getImpl(int index) {
    return new TDataProviderPtr(native_implJNI.TVector_TDataProviderPtr_getImpl(swigCPtr, this, index), false);
  }

  public TDataProviderPtr setImpl(int index, TDataProviderPtr element) {
    return new TDataProviderPtr(native_implJNI.TVector_TDataProviderPtr_setImpl(swigCPtr, this, index, TDataProviderPtr.getCPtr(element), element), true);
  }

  public int sizeImpl() {
    return native_implJNI.TVector_TDataProviderPtr_sizeImpl(swigCPtr, this);
  }

  public void addImpl(TDataProviderPtr element) {
    native_implJNI.TVector_TDataProviderPtr_addImpl__SWIG_0(swigCPtr, this, TDataProviderPtr.getCPtr(element), element);
  }

  public void addImpl(int index, TDataProviderPtr element) {
    native_implJNI.TVector_TDataProviderPtr_addImpl__SWIG_1(swigCPtr, this, index, TDataProviderPtr.getCPtr(element), element);
  }

  public TDataProviderPtr removeImpl(int index) {
    return new TDataProviderPtr(native_implJNI.TVector_TDataProviderPtr_removeImpl(swigCPtr, this, index), true);
  }

        public TVector_TDataProviderPtr(TDataProviderPtr[] elements) {
            this();
            reserve(elements.length);
            for (TDataProviderPtr element : elements) {
                addImpl(element);
            }
        }

        public TVector_TDataProviderPtr(Iterable<TDataProviderPtr> elements) {
            this();
            for (TDataProviderPtr element : elements) {
                addImpl(element);
            }
        }

        public TDataProviderPtr get(int index) {
            return getImpl(index);
        }

        public TDataProviderPtr set(int index, TDataProviderPtr element) {
            return setImpl(index, element);
        }

        public int size() {
            return sizeImpl();
        }

        public boolean add(TDataProviderPtr element) {
            modCount++;
            addImpl(element);
            return true;
        }

        public void add(int index, TDataProviderPtr element) {
            modCount++;
            addImpl(index, element);
        }

        public TDataProviderPtr remove(int index) {
            modCount++;
            return removeImpl(index);
        }

        // Generic serialization implementation - not very fast

        private void writeObject(ObjectOutputStream out) throws IOException {
            int length = this.size();
            out.writeInt(length);
            for (int i = 0; i < length; ++i) {
                out.writeObject(this.get(i));
            }
        }

        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            this.swigCPtr = native_implJNI.new_TVector_TDataProviderPtr();
            this.swigCMemOwn = true;

            int length = in.readInt();
            this.reserve(length);
            for (int i = 0; i < length; ++i) {
               this.add((TDataProviderPtr)in.readObject());
            }
        }
    
  public boolean equalsImpl(TVector_TDataProviderPtr rhs) {
    return native_implJNI.TVector_TDataProviderPtr_equalsImpl(swigCPtr, this, TVector_TDataProviderPtr.getCPtr(rhs), rhs);
  }


public boolean equals(Object obj) {
    if (obj instanceof TVector_TDataProviderPtr) {
        boolean ptrEqual = (((TVector_TDataProviderPtr)obj).swigCPtr == this.swigCPtr);
        if (ptrEqual) {
            return true;
        } else {
            return this.equalsImpl((TVector_TDataProviderPtr)obj);
        }
    } else {
        return false;
    }
}

public int hashCode() {
    return (int)this.swigCPtr;
}


  public TVector_TDataProviderPtr() {
    this(native_implJNI.new_TVector_TDataProviderPtr(), true);
  }

}
